[package]
name = "rust_rest"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = {version = "0.72", features = ["affix-state"]}
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
